import Navbar from "@/components/Navbar";
import "./globals.css";
// Swiper Styles
import "swiper/css"; // core Swiper
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/effect-fade";

import SmoothScrolling from "@/components/SmoothScrolling";

export const metadata = {
  title: "John Doe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-gilroy bg-background text-primary ">
        <SmoothScrolling>
          <Navbar />
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
