import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "John Doe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-gilroy bg-background text-primary">
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
